// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback allows `prisma generate` to succeed in CI environments
    // where DATABASE_URL is not available at build time.
    url: process.env.DATABASE_URL ?? "postgresql://placeholder:placeholder@localhost/placeholder?sslmode=require",
  },
});
